---
title: "Assigment - Data Driven Decision Making"
author: Luuc van Meegen
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

Search Youtube for a suitable business case example on data driven decision making and copy the embed code below.

<---- Watch this video if you don't know how to embed video's ---->

<iframe width="570" height="325" src="https://www.youtube.com/embed/8M5n3uhWKHE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe> dm

<---- Replace this video with your business case example ---->


## Why was data driven decision making (3DM) useful in this business case?

A company such as Netflix is an immensely successful company nowadays, with about 150 million monthly subscribers around the world they gather an enormous amount of data. Due to the existence and presence on the world wide web they put Artificial Intelligence and Data at the core of their business strategy. THe use of data driven decision making and understand of the data is a great competitive advantage for Netflix because when they understand the data they can drive and create demand by providing exactly what their audience is looking for. So, for Netflix data driven decision making is useful because it is the very core of their business strategy.


## How did the organization apply 3DM?

When Netflix wants to tap into a certain genre or audience, they release a certain type of list that provides information for example a top 10 for horror movies. This triggers the audience to watch those movies, however some movies may be boring for a fraction of the audience and some may be to scary. So, when the audience pauzes, rewinds, quits or maybe restart the movie Netflix gathers data about all those customer interactions. 

This data is then used to see which type of series and movies do well and people watch from begining till the end to create brand new content for their service. Mainly, due to their data driven decision making they know exactely what their audience wants and release something which they know will be popular. These new production are recommended to us via the use of Data and Artificial intelligence therefore they know what their audience wants to see and how to deliver the end-product to their users. 

## What can the organization do with 3DM that they couldn’t do before?

While understanding and learning from the data they gather, Netflix learned to give individual customer based recommendations, the data is analyzed in such a way that they exactely know what you like. The description of a movie differs for each person because they individually take a different scene of that movie for everyone because they know some are more interested in that part of the movie and others in another. 

